package com.coursemonitor.entity;
// Generated Apr 10, 2016 10:03:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private String courseId;
     private String courseName;
     private String academicSession;
     private String courseImg;
     private String description;
     private Set assignCourses = new HashSet(0);
     private Set assignFaculties = new HashSet(0);

    public Course() {
    }

	
    public Course(String courseId) {
        this.courseId = courseId;
    }

    public Course(String courseId, String courseName, String academicSession, String courseImg, String description) {
        this.courseId = courseId;
        this.courseName = courseName;
        this.academicSession = academicSession;
        this.courseImg = courseImg;
        this.description = description;
    }
    
    public Course(String courseId, String courseName, String academicSession, String courseImg, String description, Set assignCourses, Set assignFaculties) {
       this.courseId = courseId;
       this.courseName = courseName;
       this.academicSession = academicSession;
       this.courseImg = courseImg;
       this.description = description;
       this.assignCourses = assignCourses;
       this.assignFaculties = assignFaculties;
    }
   
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }
    public String getAcademicSession() {
        return this.academicSession;
    }
    
    public void setAcademicSession(String academicSession) {
        this.academicSession = academicSession;
    }
    public String getCourseImg() {
        return this.courseImg;
    }
    
    public void setCourseImg(String courseImg) {
        this.courseImg = courseImg;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getAssignCourses() {
        return this.assignCourses;
    }
    
    public void setAssignCourses(Set assignCourses) {
        this.assignCourses = assignCourses;
    }
    public Set getAssignFaculties() {
        return this.assignFaculties;
    }
    
    public void setAssignFaculties(Set assignFaculties) {
        this.assignFaculties = assignFaculties;
    }




}


