package com.coursemonitor.entity;
// Generated Apr 10, 2016 10:03:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dlt generated by hbm2java
 */
public class Dlt  implements java.io.Serializable {


     private int dltId;
     private String dltName;
     private String dltEmail;
     private Set assignFaculties = new HashSet(0);

    public Dlt() {
    }

    public Dlt(int dltId, String dltName, String dltEmail) {
        this.dltId = dltId;
        this.dltName = dltName;
        this.dltEmail = dltEmail;
    }

	
    public Dlt(int dltId) {
        this.dltId = dltId;
    }
    public Dlt(int dltId, String dltName, String dltEmail, Set assignFaculties) {
       this.dltId = dltId;
       this.dltName = dltName;
       this.dltEmail = dltEmail;
       this.assignFaculties = assignFaculties;
    }
   
    public int getDltId() {
        return this.dltId;
    }
    
    public void setDltId(int dltId) {
        this.dltId = dltId;
    }
    public String getDltName() {
        return this.dltName;
    }
    
    public void setDltName(String dltName) {
        this.dltName = dltName;
    }
    public String getDltEmail() {
        return this.dltEmail;
    }
    
    public void setDltEmail(String dltEmail) {
        this.dltEmail = dltEmail;
    }
    public Set getAssignFaculties() {
        return this.assignFaculties;
    }
    
    public void setAssignFaculties(Set assignFaculties) {
        this.assignFaculties = assignFaculties;
    }




}


