package com.coursemonitor.entity;
// Generated Apr 10, 2016 10:03:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Faculty generated by hbm2java
 */
public class Faculty  implements java.io.Serializable {


     private int facultyId;
     private String falcutyName;
     private Set assignFaculties = new HashSet(0);

    public Faculty() {
    }

	
    public Faculty(int facultyId) {
        this.facultyId = facultyId;
    }
    public Faculty(int facultyId, String falcutyName, Set assignFaculties) {
       this.facultyId = facultyId;
       this.falcutyName = falcutyName;
       this.assignFaculties = assignFaculties;
    }
   
    public int getFacultyId() {
        return this.facultyId;
    }
    
    public void setFacultyId(int facultyId) {
        this.facultyId = facultyId;
    }
    public String getFalcutyName() {
        return this.falcutyName;
    }
    
    public void setFalcutyName(String falcutyName) {
        this.falcutyName = falcutyName;
    }
    public Set getAssignFaculties() {
        return this.assignFaculties;
    }
    
    public void setAssignFaculties(Set assignFaculties) {
        this.assignFaculties = assignFaculties;
    }




}


