package com.coursemonitor.entity;
// Generated Mar 28, 2016 9:57:55 PM by Hibernate Tools 4.3.1



/**
 * ManagementStaff generated by hbm2java
 */
public class ManagementStaff  implements java.io.Serializable {


     private int msId;
     private Faculty faculty;
     private String msName;
     private String msEmail;
     private String msUsername;
     private String msPassword;
     private String msRole;

    public ManagementStaff() {
    }

	
    public ManagementStaff(int msId) {
        this.msId = msId;
    }
    public ManagementStaff(int msId, Faculty faculty, String msName, String msEmail, String msUsername, String msPassword, String msRole) {
       this.msId = msId;
       this.faculty = faculty;
       this.msName = msName;
       this.msEmail = msEmail;
       this.msUsername = msUsername;
       this.msPassword = msPassword;
       this.msRole = msRole;
    }
   
    public int getMsId() {
        return this.msId;
    }
    
    public void setMsId(int msId) {
        this.msId = msId;
    }
    public Faculty getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }
    public String getMsName() {
        return this.msName;
    }
    
    public void setMsName(String msName) {
        this.msName = msName;
    }
    public String getMsEmail() {
        return this.msEmail;
    }
    
    public void setMsEmail(String msEmail) {
        this.msEmail = msEmail;
    }
    public String getMsUsername() {
        return this.msUsername;
    }
    
    public void setMsUsername(String msUsername) {
        this.msUsername = msUsername;
    }
    public String getMsPassword() {
        return this.msPassword;
    }
    
    public void setMsPassword(String msPassword) {
        this.msPassword = msPassword;
    }
    public String getMsRole() {
        return this.msRole;
    }
    
    public void setMsRole(String msRole) {
        this.msRole = msRole;
    }




}


