package com.coursemonitor.entity;
// Generated Apr 10, 2016 10:03:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pvc generated by hbm2java
 */
public class Pvc  implements java.io.Serializable {


     private int pvcId;
     private String pvcName;
     private String pvcEmail;
     private Set assignFaculties = new HashSet(0);

    public Pvc() {
    }

    public Pvc(int pvcId, String pvcName, String pvcEmail) {
        this.pvcId = pvcId;
        this.pvcName = pvcName;
        this.pvcEmail = pvcEmail;
    }

	
    public Pvc(int pvcId) {
        this.pvcId = pvcId;
    }
    public Pvc(int pvcId, String pvcName, String pvcEmail, Set assignFaculties) {
       this.pvcId = pvcId;
       this.pvcName = pvcName;
       this.pvcEmail = pvcEmail;
       this.assignFaculties = assignFaculties;
    }
   
    public int getPvcId() {
        return this.pvcId;
    }
    
    public void setPvcId(int pvcId) {
        this.pvcId = pvcId;
    }
    public String getPvcName() {
        return this.pvcName;
    }
    
    public void setPvcName(String pvcName) {
        this.pvcName = pvcName;
    }
    public String getPvcEmail() {
        return this.pvcEmail;
    }
    
    public void setPvcEmail(String pvcEmail) {
        this.pvcEmail = pvcEmail;
    }
    public Set getAssignFaculties() {
        return this.assignFaculties;
    }
    
    public void setAssignFaculties(Set assignFaculties) {
        this.assignFaculties = assignFaculties;
    }




}


