package com.coursemonitor.entity;
// Generated Mar 28, 2016 9:57:55 PM by Hibernate Tools 4.3.1



/**
 * Report generated by hbm2java
 */
public class Report  implements java.io.Serializable {


     private int reportId;
     private Course course;
     private Staff staffByClId;
     private Staff staffByCmId;
     private Integer year;
     private String description;
     private Integer status;
     private String comment;

    public Report() {
    }

	
    public Report(int reportId) {
        this.reportId = reportId;
    }
    public Report(int reportId, Course course, Staff staffByClId, Staff staffByCmId, Integer year, String description, Integer status) {
       this.reportId = reportId;
       this.course = course;
       this.staffByClId = staffByClId;
       this.staffByCmId = staffByCmId;
       this.year = year;
       this.description = description;
       this.status = status;
    }
    
    
    public Report(Course course, Staff staffByClId, Staff staffByCmId, Integer year, String description, Integer status) {
       this.course = course;
       this.staffByClId = staffByClId;
       this.staffByCmId = staffByCmId;
       this.year = year;
       this.description = description;
       this.status = status;
    }
   
    public int getReportId() {
        return this.reportId;
    }
    
    public void setReportId(int reportId) {
        this.reportId = reportId;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Staff getStaffByClId() {
        return this.staffByClId;
    }
    
    public void setStaffByClId(Staff staffByClId) {
        this.staffByClId = staffByClId;
    }
    public Staff getStaffByCmId() {
        return this.staffByCmId;
    }
    
    public void setStaffByCmId(Staff staffByCmId) {
        this.staffByCmId = staffByCmId;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }




}


